services:
  backend:
    build:
      context: ./backend
    container_name: geo-backend
    ports:
      - "8000:8000"

  gateway:
    build:
      context: ./gateway
    container_name: geo-gateway
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - PORT=3001
      - BACKEND_URL=http://backend:8000

  frontend:
    build:
      context: ./frontend
    container_name: geo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
