FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package*.json .
RUN npm install

# Copy the app files (except those in .dockerignore)
COPY . .

# Run the server
CMD ["npm", "run", "start:dev"]